### ISSUE TITLE
ths url is  not found 

### ISSUE THREAD

**Issue by w796933** [theraw/The-World-Is-Yours#11]
wget https://raw.githubusercontent.com/systemroot/my-nginx/master/nginx-as-firewall/setup  
is  404 .

**Comment by theraw** [comment]
can you tell me which part of script did you run and what is your OS? 
my old account got deleted and there are some clean up to do sorry about that

**Comment by theraw** [comment]
i'm closing the issue since i didn't got a response from you, it may have been a github cache or a old pr clone so if you still see same problem please let me know!
