### ISSUE TITLE
support ubuntu 18.04

### ISSUE THREAD

**Issue by karam1ashqar** [theraw/The-World-Is-Yours#12]
I tried to do ./install in my terminal but nothing occurs

I use ubuntu 18.04

**Comment by theraw** [comment]
What does cat /etc/*-release 
Returns on your server?

**Comment by karam1ashqar** [comment]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by theraw** [comment]
Sorry 18.10 is supported not 18.04!

I'm on vacation can't help you now.
You can open install script and replace 'cosmic' with 'bionic' and then execute it'll work but i have some doubts for fail2ban..
