### ISSUE TITLE
An issue with installing LuaJIT

### ISSUE THREAD

**Issue by TechFocus** [theraw/The-World-Is-Yours#13]
I've got this error after installation
https://i.imgur.com/o9YmkhP.png

And I can't start nginx because `/usr/sbin/nginx` does not exist

When tried to install nginx manually from `/opt/nginx/sources/nginx-1.15.5` but I got an error
https://i.imgur.com/gSTDFLe.png

```bash 
adding module in /opt/nginx/modules/lua-nginx-module
checking for LuaJIT 2.x ... not found
    ./configure: error: unsupported LuaJIT version; ngx_http_lua_module requires LuaJIT 2.x.
```

**Comment by theraw** [comment]
Something must be wrong on your server try executing

```
cd /opt/nginx/modules/
             git clone http://luajit.org/git/luajit-2.0.git
             cd luajit-2.0/
             make -j`nproc`
             sudo make install
             ldconfig
```
And let me know the end of it this is the lart where the script installs luajit
