### ISSUE TITLE
Error on Ubuntu 16.04

### ISSUE THREAD

**Issue by mysticvpn** [theraw/The-World-Is-Yours#15]
I tried installing it to ubuntu 16.04 on linode but after running ./install nothing happens

**Comment by theraw** [comment]
can you post output of `cat /etc/*-release`

**Comment by mysticvpn** [comment]
thanks it went thought but this is the error after

"Executing /lib/systemd/systemd-sysv-install enable nginx
nginx: no process found
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details."

**Comment by theraw** [comment]
you have to scroll up and give me the error that just says nginx not found doesn't help me to understand what's wrong

**Comment by theraw** [comment]
there has been published one fix for one error that caused script to fail compile please try to re'compile again in a fresh server and feel free to ping me if you still have problems

**Comment by mysticvpn** [comment]
I dont know I have tried this

apt-get install build-essential libssl-dev curl nano wget zip unzip sudo git psmisc -y
curl -s https://raw.githubusercontent.com/theraw/The-World-Is-Yours/master/install > install
bash install

but still error

![image](https://user-images.githubusercontent.com/37581348/120090142-be4a5480-c132-11eb-8a7e-5cb50415de82.png)

**Comment by mysticvpn** [comment]
this is the result when I journalctl -x

-- Unit nginx.service has begun starting up.
May 30 02:33:02 localhost nginx[19470]: nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openrest
May 30 02:33:02 localhost nginx[19470]: nginx: [alert] failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/e
May 30 02:33:02 localhost nginx[19470]:         no field package.preload['resty.core']
May 30 02:33:02 localhost nginx[19470]:         no file './resty/core.lua'
May 30 02:33:02 localhost nginx[19470]:         no file '/usr/local/LuaJIT/share/luajit-2.0.5/resty/core.lua'
May 30 02:33:02 localhost nginx[19470]:         no file '/usr/local/share/lua/5.1/resty/core.lua'
May 30 02:33:02 localhost nginx[19470]:         no file '/usr/local/share/lua/5.1/resty/core/init.lua'
May 30 02:33:02 localhost nginx[19470]:         no file '/usr/local/LuaJIT/share/lua/5.1/resty/core.lua'
May 30 02:33:02 localhost nginx[19470]:         no file '/usr/local/LuaJIT/share/lua/5.1/resty/core/init.lua'
May 30 02:33:02 localhost nginx[19470]:         no file './resty/core.so'
May 30 02:33:02 localhost nginx[19470]:         no file '/usr/local/lib/lua/5.1/resty/core.so'
May 30 02:33:02 localhost nginx[19470]:         no file '/usr/local/LuaJIT/lib/lua/5.1/resty/core.so'
May 30 02:33:02 localhost nginx[19470]:         no file '/usr/local/lib/lua/5.1/loadall.so'
May 30 02:33:02 localhost nginx[19470]:         no file './resty.so'
May 30 02:33:02 localhost nginx[19470]:         no file '/usr/local/lib/lua/5.1/resty.so'
May 30 02:33:02 localhost nginx[19470]:         no file '/usr/local/LuaJIT/lib/lua/5.1/resty.so'
May 30 02:33:02 localhost nginx[19470]:         no file '/usr/local/lib/lua/5.1/loadall.so') in /nginx/nginx.conf:121
May 30 02:33:02 localhost systemd[1]: nginx.service: Control process exited, code=exited status=1
May 30 02:33:02 localhost systemd[1]: Failed to start A high performance web server and a reverse proxy server.
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit nginx.service has failed.
--
-- The result is failed.

**Comment by mysticvpn** [comment]
and this is the code when I tried service nginx status

● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/etc/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2021-05-30 02:33:02 UTC; 9min ago
  Process: 19435 ExecStop=/sbin/start-stop-daemon --quiet --stop --retry QUIT/5 --pidfile /run/nginx.pid (code=exited, status=1/FAILURE)
  Process: 19470 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=1/FAILURE)
  Process: 19467 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)

May 30 02:33:02 localhost nginx[19470]:         no file '/usr/local/LuaJIT/lib/lua/5.1/resty/core.so'
May 30 02:33:02 localhost nginx[19470]:         no file '/usr/local/lib/lua/5.1/loadall.so'
May 30 02:33:02 localhost nginx[19470]:         no file './resty.so'
May 30 02:33:02 localhost nginx[19470]:         no file '/usr/local/lib/lua/5.1/resty.so'
May 30 02:33:02 localhost nginx[19470]:         no file '/usr/local/LuaJIT/lib/lua/5.1/resty.so'
May 30 02:33:02 localhost nginx[19470]:         no file '/usr/local/lib/lua/5.1/loadall.so') in /nginx/nginx.conf:121
May 30 02:33:02 localhost systemd[1]: nginx.service: Control process exited, code=exited status=1
May 30 02:33:02 localhost systemd[1]: Failed to start A high performance web server and a reverse proxy server.
May 30 02:33:02 localhost systemd[1]: nginx.service: Unit entered failed state.
May 30 02:33:02 localhost systemd[1]: nginx.service: Failed with result 'exit-code'.

**Comment by mysticvpn** [comment]
ip: 45.118.132.44
username: root
root pass: Lin00de

thats the vps that I installed

**Comment by theraw** [comment]
openresty stopped supporting nginx, so u'll have to use an older version of lua-nginx module 

installation script is updated i already fixed your problem as i said on discord but you can try a fresh install if you want and let me know if there's smth wrong.
