### ISSUE TITLE
unsupported LuaJIT Version

### ISSUE THREAD

**Issue by m1lc0lm** [theraw/The-World-Is-Yours#16]
When i try to install it fails because of the error:

checking for LuaJIT 2.x . . . not found
     ./configure: error: unsupported LuaJIT version; ngx_http_lua_module requires LuaJIT 2.x.

I already tried to install manualy, but it not worked because of this error.

**Comment by theraw** [comment]
please post `cat /etc/*-release`

**Comment by m1lc0lm** [comment]
Right now i have this problem when starting nginx
no file './resty/core.so'
no file '/usr/local/lib/lua/5.1/resty/core.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
no file './resty.so'
no file '/usr/local/lib/lua/5.1/resty.so'
no file '/usr/local/lib/lua/5.1/loadall.so') in /nginx/nginx.conf:122

**Comment by m1lc0lm** [comment]
And for your Question:
root@malcolm-Standard-PC-i440FX-PIIX-1996:~/The-World-Is-Yours# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by theraw** [comment]
can you manually execute these and let me know the how it goes
```
             cd /opt/nginx/modules/
             git clone http://luajit.org/git/luajit-2.0.git
             cd luajit-2.0/
             make -j`nproc`
             sudo make install
             ldconfig
```

**Comment by m1lc0lm** [comment]
It has already compiled with success, but the files it wrote: no file './resty/core.so'
no file '/usr/local/lib/lua/5.1/resty/core.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
no file './resty.so'
no file '/usr/local/lib/lua/5.1/resty.so'
no file '/usr/local/lib/lua/5.1/loadall.so') in /nginx/nginx.conf:122 are missing

**Comment by theraw** [comment]
can you post your `/nginx/nginx.conf:122` ?

**Comment by m1lc0lm** [comment]
`root@malcolm-Standard-PC-i440FX-PIIX-1996:/home# cat /nginx/nginx.conf
# Suggestions? => https://github.com/theraw/The-World-Is-Yours/issues
# Problems?    => https://github.com/theraw/The-World-Is-Yours/issues
# Errors?      => https://github.com/theraw/The-World-Is-Yours/issues
user nginx;
pid /var/run/nginx.pid;
worker_processes auto;
worker_rlimit_nofile 65535;

events {
    multi_accept on;
    use epoll;
    worker_connections 65535;
}

http {
    # ////////////////////////////////////////////////////// #
    # =================== START L7 ========================= #
    # turn this 'on' if you want to use L7 For every domain hosted in your server
    testcookie on;
    testcookie_name RatschHost-L7-Protection;
    testcookie_secret random;
    testcookie_session $remote_addr;
    #testcookie_arg GO;
    testcookie_httponly_flag on;
    testcookie_max_attempts 3;
    testcookie_secure_flag on;
    testcookie_get_only on;
    testcookie_p3p 'CP="CUR ADM OUR NOR STA NID", policyref="/w3c/p3p.xml"';
    testcookie_fallback /cookies.html?backurl=$scheme://$host$request_uri;

    # Those are some ip's whitelisted by me. mostly are search engines. But not everything!
    testcookie_whitelist {
        8.8.8.8/32;
        127.0.0.1/32;
        # I don't suggest using alot of IPs here as this whitelist can fail!.
    }
    testcookie_redirect_via_refresh on;
    testcookie_refresh_encrypt_cookie on;
    testcookie_refresh_encrypt_cookie_key random;
    testcookie_refresh_encrypt_cookie_iv random;
    testcookie_refresh_template '<html><head><meta http-equiv="refresh" content="0; $testcookie_nexturl"><title>Just a moment please...</title></head><body> </script><script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script><script type=\"text/javascript\" src="//proxy2.dopehosting.net/aes.min.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("$testcookie_enc_key"),b=toNumbers("$testcookie_enc_iv"),c=toNumbers("$testcookie_enc_set");document.cookie="DOPEHOSTING="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/";</script></body></html>';
    # ===================== END L7 ========================= #
    # ////////////////////////////////////////////////////// #

    # ////////////////////////////////////////////////////// #
    # ===================== LOGS =========================== #
    log_format main '$remote_addr  |==| $status |==| $request |==| $time_local';
    # -------------------------------------------------------#
    log_format agent '$remote_addr |==| $status |==| $request |==| $http_user_agent';
    # -------------------------------------------------------#
    log_format full '$remote_addr  |==| $remote_user |==| $time_local |==| $request |==| $status |==| $body_bytes_sent |==| $http_referer |==| $http_user_agent |==| $http_x_forwarded_for';
    # =================== END LOGS ========================= #
    # ////////////////////////////////////////////////////// #

    # ////////////////////////////////////////////////////// #
    # ===================== GEIP =========================== #
    geoip2 /nginx/db/GeoLite2-Country.mmdb {
        $geoip2_data_country_code default=US country iso_code;
        $geoip2_data_country_name country names en;
    }

    # EX Ban China!
    #map $geoip2_data_country_code $allowed_country {
    #    default yes;
    #    CN no;
    #}
    # =================== END GEIP ========================= #
    # ////////////////////////////////////////////////////// #

    # ////////////////////////////////////////////////////// #
    # ===================== EXTRA ========================== #
    # Don't Go with "Nginx Can Handle Everything" !
    limit_conn_zone $server_name zone=max:1m;
    limit_req_zone $binary_remote_addr zone=one:1m rate=1r/s;
    # =================== END EXTRA ======================== #
    # ////////////////////////////////////////////////////// #

    # ////////////////////////////////////////////////////// #
    # ==================== BACKENDS ======================== #
    map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
    }

    # Example Of Backend
    #upstream varnish {
    #    zone tcp_servers 64k;
    #    server 10.10.10.39:80;
    #}
    # =================== END BACKENDS ===================== #
    # ////////////////////////////////////////////////////// #

    # ////////////////////////////////////////////////////// #
    # ==================== GENERAL ========================= #
    client_body_buffer_size        1M;
    client_header_buffer_size      1M;
    client_body_timeout            90s;
    client_header_timeout          90s;
    client_max_body_size           2M;
    keepalive_timeout              10s;
    port_in_redirect               off;
    sendfile                       on;
    server_names_hash_bucket_size  6969;
    server_name_in_redirect        off;
    server_tokens                  off;
    tcp_nodelay                    on;
    tcp_nopush                     on;
    types_hash_max_size            2048;
    resolver                       8.8.8.8 8.8.4.4;
    default_type                   application/octet-stream;
    include                        /nginx/mime.types;
    # =================== END GENERAL ====================== #
    # ////////////////////////////////////////////////////// #

    # ////////////////////////////////////////////////////// #
    # =================== LOAD CONFIGS ===================== #
    include /nginx/live/*;
    include /nginx/conf.d/*;
    include /nginx/naxsi_core.rules;
    # =================== END CONFIGS ====================== #
    # ////////////////////////////////////////////////////// #
}`

**Comment by theraw** [comment]
that's weird, unless nginx 19.9 changed somethings
try to add `lua_load_resty_core off;` below `http {` and do `service nginx restart` let me know if it works

**Comment by m1lc0lm** [comment]
The bracket is 122

**Comment by m1lc0lm** [comment]
no file './resty/
no file '/usr/local/lib/lua/5.1/resty/
no file '/usr/local/lib/lua/5.1/
no file './
no file '/usr/local/lib/lua/5.1/
no file '/usr/local/lib/lua/5.1/loadall.so') in /nginx/nginx.conf:123

**Comment by m1lc0lm** [comment]
i only added your line

**Comment by theraw** [comment]
do you have any custom config that includes openresty? or did you try to install openresty lua on your server?

**Comment by m1lc0lm** [comment]
no, i use a fresh install of ubuntu 16.04 and only installed your script.

**Comment by m1lc0lm** [comment]
the only thing i added to your script was an export, so the compiler can find the luajit

**Comment by m1lc0lm** [comment]
The complete error:
Mai 29 19:02:34 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[12819]: nginx: [warn] lua_load_resty_core is deprecated (the lua-resty-core library is required since ngx_lua v0.10.16) in /nginx/nginx.conf:16
Mai 29 19:02:34 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[12822]: nginx: [warn] lua_load_resty_core is deprecated (the lua-resty-core library is required since ngx_lua v0.10.16) in /nginx/nginx.conf:16
Mai 29 19:02:34 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[12822]: nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
Mai 29 19:02:34 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[12822]: nginx: [alert] failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: module 'resty.core' not found:
Mai 29 19:02:34 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[12822]:         no field package.preload['resty.core']
Mai 29 19:02:34 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[12822]:         no file '/usr/local/lib/lua/resty/core.lua'
Mai 29 19:02:34 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[12822]:         no file './resty/core.lua'
Mai 29 19:02:34 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[12822]:         no file '/usr/local/share/luajit-2.1.0-beta3/resty/core.lua'
Mai 29 19:02:34 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[12822]:         no file '/usr/local/share/lua/5.1/resty/core.lua'
Mai 29 19:02:34 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[12822]:         no file '/usr/local/share/lua/5.1/resty/core/init.lua'
Mai 29 19:02:34 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[12822]:         no file './resty/core.so'
Mai 29 19:02:34 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[12822]:         no file '/usr/local/lib/lua/5.1/resty/core.so'
Mai 29 19:02:34 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[12822]:         no file '/usr/local/lib/lua/5.1/loadall.so'
Mai 29 19:02:34 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[12822]:         no file './resty.so'
Mai 29 19:02:34 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[12822]:         no file '/usr/local/lib/lua/5.1/resty.so'
Mai 29 19:02:34 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[12822]:         no file '/usr/local/lib/lua/5.1/loadall.so') in /nginx/nginx.conf:124
Mai 29 19:02:34 malcolm-Standard-PC-i440FX-PIIX-1996 systemd[1]: nginx.service: Control process exited, code=exited status=1
Mai 29 19:02:34 malcolm-Standard-PC-i440FX-PIIX-1996 systemd[1]: Failed to start A high performance web server and a reverse proxy server.

**Comment by theraw** [comment]
can you try latest version of luajit
```cd /tmp/ && git clone https://luajit.org/git/luajit.git && cd luajit && make -j`nproc` && sudo make install && ldconfig```

**Comment by m1lc0lm** [comment]
No it not worked...

**Comment by theraw** [comment]
i updated the script and it should work just fine now, however it gonna take few hours to be public cause of github caches in your case you can simple execute this script and it will fix your problem, 

Careful this will delete all /nginx folder and re'create the default one so backup if you need

```
wget https://gist.githubusercontent.com/theraw/2a1fe68f8d70d49551533328237a9476/raw/a81a8541dfb1b427c806be137e498b34f499fee9/luajitpath
bash luajitpath
```

**Comment by m1lc0lm** [comment]
Again:
Mai 29 20:32:45 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[19501]: nginx: [alert] failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty relea
Mai 29 20:32:45 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[19501]:         no field package.preload['resty.core']
Mai 29 20:32:45 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[19501]:         no file './resty/core.lua'
Mai 29 20:32:45 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[19501]:         no file '/usr/local/LuaJIT/share/luajit-2.1.0-beta3/resty/core.lua'
Mai 29 20:32:45 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[19501]:         no file '/usr/local/share/lua/5.1/resty/core.lua'
Mai 29 20:32:45 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[19501]:         no file '/usr/local/share/lua/5.1/resty/core/init.lua'
Mai 29 20:32:45 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[19501]:         no file '/usr/local/LuaJIT/share/lua/5.1/resty/core.lua'
Mai 29 20:32:45 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[19501]:         no file '/usr/local/LuaJIT/share/lua/5.1/resty/core/init.lua'
Mai 29 20:32:45 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[19501]:         no file './resty/core.so'
Mai 29 20:32:45 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[19501]:         no file '/usr/local/lib/lua/5.1/resty/core.so'
Mai 29 20:32:45 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[19501]:         no file '/usr/local/LuaJIT/lib/lua/5.1/resty/core.so'
Mai 29 20:32:45 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[19501]:         no file '/usr/local/lib/lua/5.1/loadall.so'
Mai 29 20:32:45 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[19501]:         no file './resty.so'
Mai 29 20:32:45 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[19501]:         no file '/usr/local/lib/lua/5.1/resty.so'
Mai 29 20:32:45 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[19501]:         no file '/usr/local/LuaJIT/lib/lua/5.1/resty.so'
Mai 29 20:32:45 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[19501]:         no file '/usr/local/lib/lua/5.1/loadall.so') in /nginx/nginx.conf:121

**Comment by m1lc0lm** [comment]
and i used a fresh installed ubuntu server with your script

**Comment by theraw** [comment]
/usr/local/LuaJIT/share/luajit-2.1.0-beta3/resty/core.lua

the script i gave you its luajit 2.0.5 there's some misconfiguration on your part can you tell me what happens if you do this 

```
cd /opt/nginx/sources/nginx-1.19.9/
curl -s https://gist.githubusercontent.com/theraw/bbbb096c9031493e54b11c687cda974a/raw/2abd802ad65d0b9449393a849cd2be56a107301c/nnbuild.sh > nbuild.sh
bash nbuild.sh
```

**Comment by m1lc0lm** [comment]
it can build it

**Comment by m1lc0lm** [comment]
but when i start nginx, the same error occures

**Comment by m1lc0lm** [comment]
i try another reinstall to fresh ubuntu and try install it again

**Comment by theraw** [comment]
add `lua_package_path "/usr/local/LuaJIT/lib/?.lua;;";`
at nginx.conf and restart

**Comment by theraw** [comment]
if that doesn't work then try `lua_package_path "/usr/local/LuaJIT/?.lua;;";`

if that doesn't work again then only way is fresh install idk what you've done

**Comment by m1lc0lm** [comment]
i'm reinstalling the server right now. I install it and add lua_package_path to nginx config. i will answer if i am done.

**Comment by theraw** [comment]
>i'm reinstalling the server right now. I install it and add lua_package_path to nginx config. i will answer when i am done.

on fresh install you don't need to add anything just execute this and let me know if there's some problem
```
apt-get install build-essential libssl-dev curl nano wget zip unzip sudo git psmisc -y
curl -s https://raw.githubusercontent.com/theraw/The-World-Is-Yours/master/install > install
bash install
```
if you edit the script then problems could happen and i don't have much ideas how to help you

**Comment by m1lc0lm** [comment]
i forked it, but tried with your scripts. i edit something to see if it fix it, to send it to you, so you can fix it :)

**Comment by theraw** [comment]
that fork is out of date and cannot be merged

**Comment by m1lc0lm** [comment]
i've done it after your change

**Comment by m1lc0lm** [comment]
It is installing right now with:
apt-get install build-essential libssl-dev curl nano wget zip unzip sudo git psmisc -y
git clone https://github.com/theraw/The-World-Is-Yours.git
cd The-World-Is-Yours/; chmod +x *
./install

**Comment by theraw** [comment]
https://github.com/m1lc0lm/The-World-Is-Yours/blob/master/install#L289 this is not what you should be using because its meant for OpenResty (https://openresty.org/en/) not Nginx.

**Comment by m1lc0lm** [comment]
Aaaah ok.

**Comment by m1lc0lm** [comment]
Complete with your script:
Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[18793]: nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (
Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[18793]: nginx: [alert] failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty relea
Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[18793]:         no field package.preload['resty.core']
Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[18793]:         no file './resty/core.lua'
Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[18793]:         no file '/usr/local/LuaJIT/share/luajit-2.0.5/resty/core.lua'
Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[18793]:         no file '/usr/local/share/lua/5.1/resty/core.lua'
Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[18793]:         no file '/usr/local/share/lua/5.1/resty/core/init.lua'
Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[18793]:         no file '/usr/local/LuaJIT/share/lua/5.1/resty/core.lua'
Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[18793]:         no file '/usr/local/LuaJIT/share/lua/5.1/resty/core/init.lua'
Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[18793]:         no file './resty/core.so'
Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[18793]:         no file '/usr/local/lib/lua/5.1/resty/core.so'
Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[18793]:         no file '/usr/local/LuaJIT/lib/lua/5.1/resty/core.so'
Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[18793]:         no file '/usr/local/lib/lua/5.1/loadall.so'
Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[18793]:         no file './resty.so'
Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[18793]:         no file '/usr/local/lib/lua/5.1/resty.so'
Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[18793]:         no file '/usr/local/LuaJIT/lib/lua/5.1/resty.so'
Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[18793]:         no file '/usr/local/lib/lua/5.1/loadall.so') in /nginx/nginx.conf:121
Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 systemd[1]: nginx.service: Control process exited, code=exited status=1

**Comment by m1lc0lm** [comment]
on an fresh install ubuntu server

**Comment by m1lc0lm** [comment]
I fixed it. It now works
You can find my changes in my fork in a few mintes

**Comment by m1lc0lm** [comment]
But its is only for Ubuntu 16.04 LTS

**Comment by m1lc0lm** [comment]
Its up and running. The only thing, i get testcookie not to function correcly, but this is not your thing.
The changes i made are on my fork. 
Have a nice day :)

**Comment by theraw** [comment]
>Mai 29 21:08:03 malcolm-Standard-PC-i440FX-PIIX-1996 nginx[18793]: nginx: [alert] failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty relea


as your logs say you're using wrong luajit

**Comment by m1lc0lm** [comment]
like i said, it now works and i fixed it on my fork. you can see it there

**Comment by theraw** [comment]
that's not a fix, you installed openresty
