### ISSUE TITLE
Making in future proof for Ubuntu 22.04

### ISSUE THREAD

**Issue by kobayashi90** [theraw/The-World-Is-Yours#23]
It would be awesome if you update this script to work with Ubuntu 22.04
Tried fixing the distro in the code but that doesnt seem to be all.

Thanks.

**Comment by theraw** [comment]
There is plans to add more OS supports but i haven't had time to do it there's few changes to be done about that and needs some time testing and compiling modules but i'm on travel for work so i'm busy and away from my PC.
