### ISSUE TITLE
FastCGI error

### ISSUE THREAD

**Issue by Bagerter** [theraw/The-World-Is-Yours#25]
*7 connect() to unix:/var/run/php/php7.4-fpm.sock failed (13: Permission denied) while connecting to upstream, client: 174.228.128.104, server: gadgacademia.online, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host:

        location ~ \.php$ {
                include /nginx/fastcgi.conf;
                fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        }

**Comment by Bagerter** [comment]
fixed, who have this error change user in nginx.conf from user nginx; to user www-data;

**Comment by theraw** [comment]
`www-data` is usually used for apache2. after installation you should have `nginx` as for your user.  so the php sock and your web files should be chowned as nginx.
