### ISSUE TITLE
Fail2Ban Service Not Starting 

### ISSUE THREAD

**Issue by arun81** [theraw/The-World-Is-Yours#7]
Hi Team 

We have a problem when are enabling Fail2ban Service .

in line 138 of jail.local 

root@ubuntu:/opt/The-World-Is-Yours/iptables# sudo service fail2ban force-start
 * Starting authentication failure monitor fail2ban                                                                                                                     ERROR  Failed during configuration: While reading from '/etc/fail2ban/jail.local' [line 138]: option 'port' in section 'pam-generic' already exists
         

Followed the Below Steps for Installing Fail2Ban

apt-get update; apt-get upgrade -y; apt-get dist-upgrade -y; apt-get autoremove -y 
 sudo apt-get install iptables-persistent 
 sudo invoke-rc.d iptables-persistent save 
 clear 
 
 
 # ======================================================================== 
 mkdir -p /firewall/iptables/bin 
 echo '#!/bin/bash' > /firewall/iptables/bin/fire.sh 
 echo 'sudo service fail2ban stop' >> /firewall/iptables/bin/fire.sh 
 echo 'nano /etc/iptables/rules.v4' >> /firewall/iptables/bin/fire.sh 
 echo 'iptables-restore < /etc/iptables/rules.v4' >> /firewall/iptables/bin/fire.sh 
 echo 'iptables-save > /etc/iptables/rules.v4' >> /firewall/iptables/bin/fire.sh 
 echo 'sudo service fail2ban start' >> /firewall/iptables/bin/fire.sh 
 ln -sf /firewall/iptables/bin/fire.sh /bin/fire 
 curl -s https://raw.githubusercontent.com/theraw/The-World-Is-Yours/master/iptables/rules > /etc/iptables/rules.v4 
 chmod +x /bin/fire 
 # ======================================================================== 
 
 
 
 
 sudo apt-get install fail2ban -y 
 sudo service fail2ban stop 
 curl -s https://raw.githubusercontent.com/theraw/The-World-Is-Yours/master/iptables/jail.local > /etc/fail2ban/jail.local 
 touch /nginx/logs/error.log 
 sudo service fail2ban start 
 clear 

Thanks

**Comment by theraw** [comment]
`already exists`

please check what's that duplicate and remove it then restart fail2ban

**Comment by arun81** [comment]
Hi Sir 
Thanks for your support and your revert .

After disabling duplicate entry port = anyport in jails.local , geeting the below error
=========================================================================================
enabled  = false
# pam-generic filter can be customized to monitor specific subset of 'tty's
filter   = pam-generic
# port actually must be irrelevant but lets leave it all for some possible uses
  port     = all
  banaction = iptables-allports
# port     = anyport
logpath  = /var/log/auth.log
maxretry = 6
============================================================================================

root@ubuntu:/etc/fail2ban# service fail2ban force-start
 * Starting authentication failure monitor fail2ban                                                                                                                     ERROR  Found no accessible config files for 'filter.d/nginx-limits' under /etc/fail2ban
ERROR  No section: 'Definition'
ERROR  No section: 'Definition'
ERROR  Unable to read the filter
ERROR  Errors in jail 'nginx-limits'. Skipping...
ERROR  Found no accessible config files for 'filter.d/nginx-ban' under /etc/fail2ban
ERROR  No section: 'Definition'
ERROR  No section: 'Definition'
ERROR  Unable to read the filter
ERROR  Errors in jail 'nginx-ban'. Skipping...
                                                           

Thanks

**Comment by theraw** [comment]
sorry for the delay..

If you still have this problem, let me know the output of `lsb_release -a`

**Comment by arun81** [comment]
Hi Sir 

Getting the below error while activating fail2ban

root@ubuntu:/opt/The-World-Is-Yours/iptables# service fail2ban force-start
 * Starting authentication failure monitor fail2ban                                                                                                                     ERROR  Failed during configuration: While reading from '/etc/fail2ban/jail.local' [line 138]: option 'port' in section 'pam-generic' already exists
                                                                                                                                                                 [fail]

Thanks

**Comment by theraw** [comment]
sorry the configuration file which i have provided on Github is for ubuntu 14.04, that's why the installation script does not automatically installs fail2ban https://github.com/theraw/The-World-Is-Yours/blob/master/install

**Comment by arun81** [comment]
Ok . Thanks for the update 

Regards

**Comment by theraw** [comment]
this is the part of code is what is used to install on ubuntu 16 https://github.com/theraw/The-World-Is-Yours/blob/master/install#L198-L377

So the error which you're getting is because you are using ubuntu 14 config file on ubuntu 16,

What i suggest in this case is to purge fail2ban, `apt-get purge --remove fail2ban` which also removes the configs, then install it again don't touch the rules just enable it

then into jail.local add those parts

1. https://github.com/theraw/The-World-Is-Yours/blob/master/iptables/jail.local#L105-L111

2. https://github.com/theraw/The-World-Is-Yours/blob/master/iptables/jail.local#L113-L118

To make those to work you need to put the 2 checks into `/etc/fail2ban/filter.d/`
https://raw.githubusercontent.com/theraw/The-World-Is-Yours/master/iptables/filter.d/nginx-limits.conf
https://raw.githubusercontent.com/theraw/The-World-Is-Yours/master/iptables/filter.d/nginx-ban.conf

Try to restart and let me know if you're getting any error.

**Comment by arun81** [comment]
Hi Sir 

It worked like a charm . Please close this ticket 

Please let us know the roadmap for this project when the GUI will be available to monitor real time logs 

Thanks

**Comment by arun81** [comment]
Please addin follow script in your repository for viewing active connection , unban ip , view banned . 
Please add in your repository .

Thanks
[TheRaw.zip](https://github.com/theraw/The-World-Is-Yours/files/2203008/TheRaw.zip)

**Comment by theraw** [comment]
That will take a lot of time because is complicated stuff and to be able to monitor sites stuff will be needed to host a site from the GUI. so it will be like an admin panel for nginx and your server.
